In [ ]:
import pandas as pd
# Sample farm dataset
data = {
 "Rainfall_mm": [200, 190, 220, 280, 190],
 "Soil_Moisture": [30, 26, 35, 33, 29],
 "Yield_kg": [3200, 3000, 3500, 3400, 3100]
}
df = pd.DataFrame(data)
df


,Rainfall_mm,Soil_Moisture,Yield_kg
0,200,30,3200
1,190,26,3000
2,220,35,3500
3,280,33,3400
4,190,29,3100


In [ ]:
from sklearn.linear_model import LinearRegression
X = df[["Rainfall_mm", "Soil_Moisture"]]
y = df["Yield_kg"]
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [ ]:
predicted_yield = model.predict(X)
predicted_yield

array([3202.5, 3002.5, 3515. , 3377.5, 3102.5])

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
# Training data: past seasons
rainfall = np.array([[200], [190], [220], [250]])
yield_kg = np.array([3200, 3350, 3500, 3400])
# Train supervised model
model = LinearRegression()
model.fit(rainfall, yield_kg)
# Predict yield for new season
model.predict([[254]])

array([3450.71428571])

In [ ]:
from sklearn.cluster import KMeans
import pandas as pd
# Soil data without labels
soil_data = pd.DataFrame({
"pH": [6.5, 6.8, 7.2, 7.5, 6.6],
"Moisture": [30, 35, 45, 50, 32]
})
# Group soil types automatically
kmeans = KMeans(n_clusters=2, random_state=0)
soil_data["Group"] = kmeans.fit_predict(soil_data)
soil_data

,pH,Moisture,Group
0,6.5,30,1
1,6.8,35,1
2,7.2,45,0
3,7.5,50,0
4,6.6,32,1


In [ ]:
import pandas as pd
data = {
 "Rainfall_mm": [180, 190, 200, 210, 220],
 "Yield_kg": [3000, 3100, 3200, 3400, 3500]
}
df = pd.DataFrame(data)

In [ ]:

# Predict yield for 205 mm rainfall
model.predict([[254]])


array([3450.71428571])